from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='SystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField()),
            ],
            options={'ordering': ('name',)},
        ),
        migrations.CreateModel(
            name='TaskInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField()),
            ],
            options={'ordering': ('name',)},
        ),
        migrations.CreateModel(
            name='PromptProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('curriculum_text', models.TextField()),
                ('seed_problem_text', models.TextField()),
                ('baseline_text', models.TextField(blank=True)),
                ('system_prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='lab.systemprompt')),
                ('task_instruction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='lab.taskinstruction')),
            ],
            options={'ordering': ('name',)},
        ),
        migrations.CreateModel(
            name='BatchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('seed_problem_override', models.TextField(blank=True)),
                ('baseline_override', models.TextField(blank=True)),
                ('repetitions', models.PositiveIntegerField(default=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('prompt_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_groups', to='lab.promptprofile')),
            ],
            options={'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='DifficultyPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('instruction_text', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('prompt_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty_presets', to='lab.promptprofile')),
            ],
            options={'ordering': ('prompt_profile', 'name'), 'unique_together': {('prompt_profile', 'name')}},
        ),
        migrations.CreateModel(
            name='StylePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('instruction_text', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('prompt_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_presets', to='lab.promptprofile')),
            ],
            options={'ordering': ('prompt_profile', 'name'), 'unique_together': {('prompt_profile', 'name')}},
        ),
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_code', models.CharField(max_length=50)),
                ('target_turns', models.PositiveIntegerField(default=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('prompt_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to='lab.promptprofile')),
            ],
            options={'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='ExperimentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('run_type', models.CharField(choices=[('single', 'Single'), ('batch', 'Batch')], default='single', max_length=20)),
                ('seed_problem_override', models.TextField(blank=True)),
                ('baseline_override', models.TextField(blank=True)),
                ('effective_seed_problem', models.TextField(blank=True)),
                ('effective_baseline', models.TextField(blank=True)),
                ('effective_difficulty', models.CharField(blank=True, max_length=80)),
                ('effective_style', models.CharField(blank=True, max_length=80)),
                ('assembled_prompt', models.TextField(blank=True)),
                ('raw_response', models.TextField(blank=True)),
                ('structured_output', models.JSONField(blank=True, default=dict)),
                ('parse_success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='lab.batchgroup')),
                ('prompt_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_runs', to='lab.promptprofile')),
            ],
            options={'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='EvaluationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('knowledge_alignment', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('difficulty_appropriateness', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('structural_completeness', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('novelty', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lab.experimentrun')),
            ],
            options={'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='LearningTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('generated_focus', models.CharField(blank=True, max_length=150)),
                ('generated_question', models.TextField()),
                ('learner_answer', models.TextField(blank=True)),
                ('difficulty_used', models.CharField(blank=True, max_length=20)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('accuracy_ratio', models.FloatField(default=0.0)),
                ('result_label', models.CharField(choices=[('pending', 'Pending'), ('correct', 'Correct'), ('partial', 'Partially Correct'), ('incorrect', 'Incorrect')], default='pending', max_length=20)),
                ('system_action', models.CharField(choices=[('keep', 'Keep current level'), ('easy', 'Generate easy follow-up'), ('medium', 'Generate medium follow-up'), ('hard', 'Generate hard follow-up'), ('end', 'End session')], default='keep', max_length=20)),
                ('question_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='lab.learningsession')),
            ],
            options={'ordering': ('round_number', 'created_at'), 'unique_together': {('learning_session', 'round_number')}},
        ),
        migrations.CreateModel(
            name='TurnGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_order', models.PositiveIntegerField(default=1)),
                ('test_input', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True)),
                ('learner_output', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('learning_turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='lab.learningturn')),
            ],
            options={'ordering': ('case_order', 'id')},
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1_topic_relevance', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q2_difficulty_appropriateness', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q3_clarity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q4_adaptive_followup', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q5_step_by_step_support', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q6_weak_point_identification', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q7_ease_of_interaction', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q8_readability', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q9_willingness_to_reuse', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q10_overall_helpfulness', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('open_helpful_part', models.TextField(blank=True)),
                ('open_problem_encountered', models.TextField(blank=True)),
                ('open_suggestion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='lab.learningsession')),
            ],
            options={'ordering': ('-created_at',)},
        ),
    ]
